In [1]:
# Import Pandas
import pandas as pd_

# Load Movies Metadata
metadata = pd_.read_csv('movie_items.csv', low_memory=False)

# Calculate C
C = metadata['vote_average'].mean()

# Calculate the minimum number of votes required to be in the chart, m
m = metadata['vote_count'].quantile(0.85)

# Filter out all qualified movies into a new DataFrame
q_movies = metadata.copy().loc[metadata['vote_count'] >= m]
q_movies.shape

# Function that computes the weighted rating of each movie
def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    # Calculation based on the IMDB formula
    return (v/(v+m) * R) + (m/(m+v) * C)

# Define a new feature 'score' and calculate its value with `weighted_rating()`
q_movies['score'] = q_movies.apply(weighted_rating, axis=1)

#Sort movies based on score calculated above
q_movies = q_movies.sort_values('score', ascending=False)

#Print the top 10 movies
q_movies[['item_', 'vote_count', 'vote_average', 'score']].head(10)

      item_  vote_count  vote_average     score
1061     50         583      4.358491  4.127836
862     318         298      4.466443  4.049013
1283     64         283      4.445230  4.019161
1467    127         413      4.283293  3.997915
1474     98         390      4.289744  3.990098
872     483         243      4.456790  3.980780
1471    174         420      4.252381  3.977863
1486     12         267      4.385768  3.961687
8       100         508      4.155512  3.938464
1517    313         350      4.245714  3.932766